### ISSUE TITLE
CUDA builds broken in nightly tests

### ISSUE THREAD

**Issue by sayerhs** [Exawind/nalu-wind#642] opened 2020-06-26 23:15 UTC
It appears that the latest Trilinos/STK update breaks builds for CUDA [CDash](https://my.cdash.org/viewBuildError.php?buildid=1845549). 

@jrood-nrel do you pass any special arch flags when building for CUDA on NREL Eagle?

**Comment by alanw0** [comment] 2020-06-27 03:13
Ugh, I think I know what's going on here. I'll push a fix as soon as I can.
I specifically built and ran nalu-wind on cuda (on ascicgpu) with the stk update. But I guess that was before a late commit went into stk to fix a AVX512 simd issue that Sparc had encountered. I guess sierra doesn't have any cuda builds where the host has AVX512...

**Comment by alanw0** [comment] 2020-06-28 23:32
A fix has been merged into Trilinos:develop. I'll take a look at the nalu-wind dashboard in the morning to see whether it worked for this eagle build.

**Comment by sayerhs** [comment] 2020-06-29 12:54
@alanw0 It appears that trilinos/trilinos#7598 didn't help the build on NREL Eagle. 

For nightly builds, @jrood-nrel usually forces the CXX flags to have `-O2 -march=skylake-avx512 -mtune=skylake-avx512` with 

```
-DKOKKOS_ARCH_SKX=ON -DKOKKOS_ARCH_VOLTA70=ON
```

Do you think that could be causing the issue?

**Comment by alanw0** [comment] 2020-06-29 14:24
@sayerhs bummer! I guess something else is weird, and my diagnosis was wrong or incomplete. I'm off on vacation for two weeks so I've referred this to the stk team. You will probably be hearing from @tasmith4 or @jvo1012 , they'll know what to do.

**Comment by tasmith4** [comment] 2020-06-29 16:33
@sayerhs or @jrood-nrel, we're looking into this, and we're trying to understand how Trilinos is being built.  Is it possible for one of you to send the spack build log for this build of Trilinos?  Is the spack package used for Trilinos the one built-in to spack or is it special?  If built-in, which version (or commit hash) of spack are you using?  If special, where can we see it?

**Comment by jrood-nrel** [comment] 2020-06-29 16:42
I have a special `cuda` variant that does this:
```
        if '+cuda' in self.spec:
            spack_env.set('NVCC_WRAPPER_DEFAULT_COMPILER', spack_cxx)
            spack_env.set('OMPI_CXX', join_path(self.stage.path, 'src', 'packages', 'kokkos', 'bin', 'nvcc_wrapper'))
            spack_env.set('MPICH_CXX', join_path(self.stage.path, 'src', 'packages', 'kokkos', 'bin', 'nvcc_wrapper'))
            spack_env.set('CUDACXX', join_path(self.spec['cuda'].prefix, 'bin', 'nvcc'))
```
Here is the most pertinent section of the Trilinos cmake configuration:
```
'-DBUILD_SHARED_LIBS:BOOL=OFF' '-DKOKKOS_ARCH:STRING=SKX;Volta70' '-DMPI_USE_COMPILER_WRAPPERS:BOOL=ON' '-DMPI_CXX_COMPILER:FILEPATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/openmpi-3.1.4-kuzrpughgfurzixeep7le673td4jjwq5/bin/mpic++' '-DMPI_C_COMPILER:FILEPATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/openmpi-3.1.4-kuzrpughgfurzixeep7le673td4jjwq5/bin/mpicc' '-DMPI_Fortran_COMPILER:FILEPATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/openmpi-3.1.4-kuzrpughgfurzixeep7le673td4jjwq5/bin/mpif90' '-DTrilinos_ENABLE_OpenMP:BOOL=OFF' '-DKokkos_ENABLE_OpenMP:BOOL=OFF' '-DTpetra_INST_OPENMP:BOOL=OFF' '-DTrilinos_ENABLE_CUDA:BOOL=ON' '-DTPL_ENABLE_CUDA:BOOL=ON' '-DCMAKE_CXX_FLAGS=--remove-duplicate-link-files' '-DKokkos_ENABLE_CUDA:BOOL=ON' '-DKokkos_ENABLE_Cuda_UVM:BOOL=ON' '-DTpetra_ENABLE_CUDA:BOOL=ON' '-DTpetra_INST_CUDA:BOOL=ON' '-DKokkos_ENABLE_Cuda_Lambda:BOOL=ON' '-DKOKKOS_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE:BOOL=ON' '-DKOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF' '-DTpetra_INST_SERIAL:BOOL=ON' '-DTrilinos_ENABLE_CXX11:BOOL=ON' '-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON' '-DTpetra_INST_DOUBLE:BOOL=ON' '-DTpetra_INST_COMPLEX_DOUBLE:BOOL=OFF' '-DTrilinos_ENABLE_TESTS:BOOL=OFF' '-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF' '-DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF' '-DTrilinos_ALLOW_NO_PACKAGES:BOOL=OFF' '-DTrilinos_ENABLE_Epetra:BOOL=OFF' '-DTrilinos_ENABLE_Tpetra:BOOL=ON' '-DTrilinos_ENABLE_KokkosKernels:BOOL=ON' '-DTrilinos_ENABLE_ML:BOOL=OFF' '-DTrilinos_ENABLE_MueLu:BOOL=ON' '-DXpetra_ENABLE_Kokkos_Refactor:BOOL=ON' '-DMueLu_ENABLE_Kokkos_Refactor:BOOL=ON' '-DTrilinos_ENABLE_EpetraExt:BOOL=OFF' '-DTrilinos_ENABLE_AztecOO:BOOL=OFF' '-DTrilinos_ENABLE_Belos:BOOL=ON' '-DTrilinos_ENABLE_Ifpack2:BOOL=ON' '-DTrilinos_ENABLE_Amesos2:BOOL=ON' '-DAmesos2_ENABLE_SuperLU:BOOL=ON' '-DAmesos2_ENABLE_KLU2:BOOL=OFF' '-DTrilinos_ENABLE_Zoltan2:BOOL=ON' '-DTrilinos_ENABLE_Ifpack:BOOL=OFF' '-DTrilinos_ENABLE_Amesos:BOOL=OFF' '-DTrilinos_ENABLE_Zoltan:BOOL=ON' '-DTrilinos_ENABLE_STK:BOOL=ON' '-DTrilinos_ENABLE_Gtest:BOOL=ON' '-DTrilinos_ENABLE_SEACASExodus:BOOL=ON' '-DTrilinos_ENABLE_SEACASEpu:BOOL=ON' '-DTrilinos_ENABLE_SEACASExodiff:BOOL=ON' '-DTrilinos_ENABLE_SEACASNemspread:BOOL=ON' '-DTrilinos_ENABLE_SEACASNemslice:BOOL=ON' '-DTrilinos_ENABLE_SEACASIoss:BOOL=ON' '-DTPL_ENABLE_MPI:BOOL=ON' '-DTPL_ENABLE_Boost:BOOL=ON' '-DBoostLib_INCLUDE_DIRS:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/boost-1.68.0-sapv6yf36ygmp6ozbu33n4yhbml7kaia/include' '-DBoostLib_LIBRARY_DIRS:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/boost-1.68.0-sapv6yf36ygmp6ozbu33n4yhbml7kaia/lib' '-DBoost_INCLUDE_DIRS:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/boost-1.68.0-sapv6yf36ygmp6ozbu33n4yhbml7kaia/include' '-DBoost_LIBRARY_DIRS:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/boost-1.68.0-sapv6yf36ygmp6ozbu33n4yhbml7kaia/lib' '-DTPL_ENABLE_SuperLU:BOOL=ON' '-DSuperLU_LIBRARY_DIRS=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/superlu-4.3-kutz7udvff4krok2ajm6t75dmrvrcr2z/lib' '-DSuperLU_INCLUDE_DIRS=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/superlu-4.3-kutz7udvff4krok2ajm6t75dmrvrcr2z/include' '-DTPL_ENABLE_Netcdf:BOOL=ON' '-DNetCDF_ROOT:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/netcdf-4.6.1-2iyrtgwxat4rz7mkcphz3qdsv3mp2cna' '-DTPL_Netcdf_PARALLEL:BOOL=ON' '-DTPL_Netcdf_Enables_Netcdf4:BOOL=ON' '-DTPL_ENABLE_Pnetcdf:BOOL=ON' '-DPNetCDF_ROOT:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/parallel-netcdf-1.8.0-ka7hw2wvax2dr5e2lhpahdwcsepxoxji' '-DTPL_ENABLE_HDF5:BOOL=ON' '-DHDF5_ROOT:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/hdf5-1.10.4-mbbc656zhrcyr4iz53egxrxnfutx2fuk' '-DHDF5_NO_SYSTEM_PATHS:BOOL=ON' '-DTPL_ENABLE_Zlib:BOOL=ON' '-DZlib_ROOT:PATH=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/zlib-1.2.11-l3pxi6wfiwbxeb7s4njasl74g53vwuez' '-DTPL_ENABLE_BLAS:BOOL=ON' '-DBLAS_LIBRARY_NAMES=blas' '-DBLAS_LIBRARY_DIRS=/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/netlib-lapack-3.8.0-c7ytzgkm3ne3oby4scffax4z2oeaasev/lib64'
```

**Comment by tasmith4** [comment] 2020-06-29 17:20
@jrood-nrel, is it possible for you to send your custom packages for trilinos and nalu-wind?

**Comment by jrood-nrel** [comment] 2020-06-29 17:27
https://github.com/Exawind/build-test/tree/master/configs/custom-package-files

**Comment by tasmith4** [comment] 2020-07-02 18:11
@sayerhs @jrood-nrel, we've been able to reproduce and create a fix for this issue, which we have successfully tested locally.  We have a [pull request](https://github.com/trilinos/Trilinos/pull/7622) against trilinos/develop containing our fix -- hopefully that will go in shortly.

**Comment by jrood-nrel** [comment] 2020-07-02 18:24
Excellent!

**Comment by tasmith4** [comment] 2020-07-06 14:18
@sayerhs @jrood-nrel -- given that we reproduced locally, I'm extremely surprised that the dashboard is still failing.  But we'll take another look at this today.

**Comment by jrood-nrel** [comment] 2020-07-06 15:48
Yeah that is unfortunate. I just verified it built the latest Trilinos `develop` `10cb4586d6` and I see your PR in the Trilinos commits. I'm trying to think if there is any information that we don't have in this issue with how the tests are building Trilinos but I think it's all here. I verified that `-O2 -march=skylake-avx512 -mtune=skylake-avx512` are explicitly used. If it really gets down to it, we can have a call and I can try to manually reproduce it on Eagle and we can work through it there if necessary.

**Comment by sayerhs** [comment] 2020-07-06 16:07
@jrood-nrel Can you attempt a build without `-march=skylake-avx512 -mtune=skylake-avx512` ?

**Comment by tasmith4** [comment] 2020-07-06 17:06
@jrood-nrel, yeah, we had built on an SNL skylake machine using exawind-builder and adjusting the flags to include `-O2 -march=skylake-avx512 -mtune=skylake-avx512`.  With this build we saw the errors before the fix and saw them go away after the fix.  So I assume there is some other subtilty with the eagle build that we were missing.  Our next move was going to be to use the build-test repo to exactly reproduce the eagle build on our local machine.

I think we could probably diagnose a day or two sooner by working with you directly on eagle, since we'd save the time of setting up build-test for our local machine, and have a guaranteed reproducer.  Totally up to you -- I'm available this afternoon to discuss, but if you'd like to see how our local experiment turns out first we are happy to go that route also and let you know.

**Comment by jrood-nrel** [comment] 2020-07-06 17:25
@tasmith4 I am available any time this afternoon. I have just manually set up a nalu-wind build on eagle using the trilinos from the tests and I am able to reproduce the error, so I will be ready to try things out. What's the best option for conferencing for you? I will try to set up a call for 1 or 2pm if that works.

**Comment by jrood-nrel** [comment] 2020-07-06 17:27
@sayerhs That is possible, but a bit more work than I would like to get that data point. I'm hoping we can work through the direct problem with this call.

**Comment by tasmith4** [comment] 2020-07-06 18:21
@jrood-nrel sounds good -- responding on Slack to coordinate details.

**Comment by tasmith4** [comment] 2020-07-06 21:13
@sayerhs @jrood-nrel new pull request is [here](https://github.com/trilinos/Trilinos/pull/7641) with the fix that worked in @jrood-nrel's local test on eagle.  Hopefully this is resolved now.

**Closed** 2020-07-10 12:57 UTC
Labels: build-issues
