### ISSUE TITLE
Nalu-Wind has build errors with Trilinos solvers enabled

### ISSUE THREAD

**Issue by psakievich** [Exawind/nalu-wind#1268] opened 2024-06-24 20:27 UTC
Closes #1264.  We believe this is the parent issue and it needs to be resolved.

**Comment by tasmith4** [comment] 2024-07-26 12:06
closing ... see comment on #1264.  was not able to reproduce the problem on `nalu-wind@master ^trilinos@15.1.1`, so do not believe there are compatibility issues with the latest version of the code

**Closed by tasmith4** 2024-07-26 12:06 UTC
Labels: bug
