### ISSUE TITLE
Openfast build error when using spack

### ISSUE THREAD

**Issue by Cfdbooks** [Exawind/nalu-wind#39] opened 2018-09-19 01:21 UTC
Compiling seem ok, an error occurs in linking process. I think the additional ";" in link option " -fexceptions;-pthread" cause this problem but don't know how to fix it. Thanks in advance.
![img_3107](https://user-images.githubusercontent.com/16715436/45725350-12b07e80-bbed-11e8-93e2-077b76048460.JPG)

**Comment by jrood-nrel** [comment] 2018-09-19 01:56
@Cfdbooks Can you try using the latest Nalu-Wind `build-test` repo? This is the replacement for the NaluSpack repo. https://github.com/Exawind/build-test Also make sure you are using the latest Spack repo on the `develop` branch.

Next, that looks like an error in OpenFAST and if you don't need OpenFAST, you can try using `~openfast` in replacement of `+openfast` in the install script.

**Comment by Cfdbooks** [comment] 2018-09-19 02:10
Thanks. I will try. I think it is not a problem in OpenFAST because Tioga has the same problem.

**Comment by Cfdbooks** [comment] 2018-09-19 03:56
@jrood-nrel  I tried and got the same error.

**Comment by jrood-nrel** [comment] 2018-10-01 17:45
@Cfdbooks I was able to spend some more time searching for the cause of this and I am unable to find any leads as to why you're having this problem. Unfortunately I will have to direct you to reporting this issue on the Spack github as it isn't a Nalu-Wind issue and doesn't seem to be a direct issue regarding the OpenFAST code as well. I think this code is somehow being injected by either Spack, or due to a specific configuration you are using or a problem specific to the configuration of your machine.

**Comment by Cfdbooks** [comment] 2018-10-02 02:48
@jrood-nrel  Thanks for your help. I thinks it is a system dependent problem. The building process is ok in Mac OS but cause the problem in Fedora 27.

**Comment by jrood-nrel** [comment] 2018-10-12 03:17
@Cfdbooks I'm seeing this error now too. It's definitely a problem with CMake since version 3.10.0 because I can use 3.9.4 and it works fine. It also appears to get added due to the CMake FindMPI module that OpenFAST is using because this error happens for other packages that use FindMPI now as well. Trilinos recently set a minimum CMake version of 3.10.0, so I will have to solve this so we can use a newer CMake. Sorry I didn't catch this earlier, but I will report back when I can solve this.

**Comment by jrood-nrel** [comment] 2018-10-17 21:10
@Cfdbooks If you would like, you can try this again with the latest Spack develop branch which should default to using CMake 3.12.3 which for me seems to fix this issue. You might also need to wait for this PR to get merged: https://github.com/spack/spack/pull/9560 which will solve other problems I was seeing with Tioga and OpenFAST that were building as static libraries and then Nalu-Wind trying to link them into a shared library without `-fPIC` having been used, causing "relocatable" errors.

**Comment by Cfdbooks** [comment] 2018-10-19 13:31
Dear Rood,

Thanks for your warm-hearted help. It works.

J.Xia

**Comment by jrood-nrel** [comment] 2018-10-19 14:06
Great!

**Closed by jrood-nrel** 2018-10-19 14:06 UTC
