### ISSUE TITLE
regression test: tolerance testing

### ISSUE THREAD

**Issue by lucbv** [Exawind/nalu-wind#255] opened 2019-06-17 16:07 UTC
This issue is meant to continue the discussion started in PR #251

**Comment by lucbv** [comment] 2019-06-17 16:15
@sayerhs @alanw0 @rcknaus 
One of the things I would like to point is the [this](https://github.com/Exawind/nalu-wind/blob/ba2d9809c1a124c136ecb1232472c4f9547b8f1d/reg_tests/CMakeLists.txt#L33) tolerance criteria.
It pretty much means that all version of the GNU compiler are supposed to lead to the exact same convergence behavior which seems pretty strict to me.
Would it be OK to have other compiler/TPL version converge up to the default tolerance for `Linux` as set [here](https://github.com/Exawind/nalu-wind/blob/ba2d9809c1a124c136ecb1232472c4f9547b8f1d/reg_tests/CMakeLists.txt#L38)?

**Comment by alanw0** [comment] 2019-06-17 17:09
@lucbv I think it's reasonable to have slightly looser tolerances for certain platforms or compilers.  The fundamental issue is that we don't want anything to change unless we understand it. i.e., we want to know if/when a code change alters the answers. If we loosen tolerances to get tests to pass, then we're just hiding stuff. As long as we maintain some tight tolerances on the nightly dashboard then we'll still be able to know if someone pushes a bad change. Perhaps ultimately we need to set up a system like Trilinos has, to do automated PR testing. That uses a controlled set of flags and libraries on certain systems, so that the results can be controlled.

**Comment by lucbv** [comment] 2019-06-17 17:18
@alanw0 I understand that the dashboard needs to have a tight tolerance for quality assurance but that can be achieved using the configure option `-D TEST_TOLERANCE=1e-N`.
On the other hand the current default for `GCC` is bit to bit equality which is pretty hard to achieve with software version deviation...
Also I have access to `clang` and `intel` compilers which I could use on my workstation to go around the tight requirement for `GCC`.
I have decided against it because it does not feel right but eventually I might resort to it to get work done.

**Comment by lucbv** [comment] 2019-06-17 17:23
@sayerhs reading [pass_fail.sh]() it seems that absolute difference between the gold file and the test file is compared to a fixed tolerance. Should not the check be performed with a relative difference?
For solutions greater than `10` there might not be enough significant digits to reach `1e-15` tolerance?

**Comment by sayerhs** [comment] 2019-06-18 05:25
@lucbv Assuming I understood your points correctly, here are my thoughts on some of the points you raised:

- The regression tests are solely for the developers, so my preference is that the developer manually use `-DTEST_TOLERANCE=<desired_value>` during CMake rather than change the defaults to something smaller. 
- I do think that the tolerance doesn't have to be as strict as `1e-15`, but I don't have a good answer for: _"should it be 1e-12 or 1e-8 or 1e-6?_
- I am not happy with the current tolerance settings for `clang` and `intel`, I feel they are too lax and probably are letting issues slide by that we should be aware of and address. However, I haven't figured out a good way to tighten the tolerances. That being said, there is still benefit to those nightly tests as Clang tests use address sanitizer and catch memory errors (almost as good as valgrind). The intel builds allow us to catch some C++/fortran features/quirks that show up as warnings/errors on Intel builds before we move the code to systems like NERSC Cori. I don't think the tolerance set for `Linux` is exercised for any of the dashboard tests, @jrood-nrel can you confirm? I think that is just some legacy code that never got cleaned up. 
- You mentioned that you were thinking of switching to `clang` or `intel` builds to show all tests passing and _get around the tight requirement for GCC_. I think that would be a bad idea, because we would be missing some legitimate issue that got swept under the rug and won't be discovered until late in the process. Instead I think your previous suggestion was the better one, download the `master` branch of `nalu-wind` generate custom golds for your specific machine and then use that to ensure that your modifications don't change the results at a tighter tolerance level, regardless of modules/builds. 
- I think we might need to introduce a per-test tolerance to allow for certain sensitive tests like `tensor_tg_mms`. I'll work on a PR for that. 
- Regarding @alanw0's point about automated PR testing, that would be a great improvement to the current setup. I have would like to see some automated CI with nalu-wind. As for user machines, I suspect that the simplest route might be to have Docker builds of the gold GCC system environment that can be used on developer machines to run final CTest before submitting the pull request. I was hoping Spack builds (with pinned `packages.py` files like we do in `exawind-builder`) might be sufficient, but it appears that there are still a few failing tests on Sandia systems. 
- Your question about `pass_fail.sh` is a good one and I will have to think about that. Looking at some example `norm.gold` files, I see that entries that always have 16 digits and I am wondering how that affects tolerance checks. @rcknaus, any comments? 

```
643731.0200954032 1 0.0666667
24949.51334018121 2 0.133333
383.5088426140573 3 0.2
102.6652985119906 4 0.266667
63.54494044664015 5 0.333333
```

Finally, I feel that the main concern when evaluating pull-requests should be whether the submitter **and** the reviewers can adequately explain the reason for the diffs (and have a good way to revert/fix things if it affects nightly tests), rather than a blanket rule that all tests must pass on user machine before things can be merged. I believe this was Alan's original concern as well in #251. For a change like the one introduced in #251, I am OK with ensuring that a subset of regression tests pass with custom gold files before/after change and then ensuring the rest with nightly dashboard (assuming we did a squash merge for easy revert). I would be interested in hearing @alanw0's thoughts on that. However, if we go that route I would like to see tagged releases that _production users of Nalu-Wind_ use rather than get bitten by buggy commits/reverts etc. The current situation of having to update `trilinos/develop` every other day just to get the same runs you did a week ago is ridiculous in my opinion.

**Comment by alanw0** [comment] 2019-06-18 15:42
@sayerhs I agree it's ok if he uses custom gold files and/or looser tolerances on his own machine, as long as we keep tight tolerances on the nightly dashboard results. He clearly understands that the goal is to figure out whether his commits change behavior before they get to the nightly dashboard. I agree with your concern about production users. We don't want to start letting bad commits in, then revert them, at least not frequently, as that will impact users who need to be able to assume some stability of results.
I don't know how to set up the automated PR testing like Trilinos has. They use a set of machines here at Sandia for those builds and test runs. We could potentially set up some machine(s) somewhere to do something like that, but I wouldn't even know how to start.

**Comment by jrood-nrel** [comment] 2019-06-18 16:41
I've read through all of this, and It seems like the original issue was solved by generating local golds and checking for diffs from the PR itself. Although not ideal, things rarely are, so that seems sufficient to me.

The default test tolerances in CMake are superfluous so feel free to do whatever you want with them. They are merely a guide with how far the tolerances stray for each configuration. I will still use `1e-15` on GCC 4.9 because that is the most portable option and much looser tolerances on all other configurations so that the tests pass. I also would guess that using tighter tolerances on any other compiler configuration wouldn't catch anything that the current `1e-15` GCC 4.9 configuration would. I'm currently testing this theory in my other project where every configuration is tested at machine precision using the physical quantities.

Each build line in the nightly tests accomplishes its own specific task that Shreyas explained and they don't try to accomplish all tasks. I also mildly disagree with per-test tolerances, but if they are unavoidable (i.e. a truly nondeterministic test), I would prefer tests to pass so there isn't a bunch of noise in the results. However, we have been making `1e-15` work for a while now.

Regarding `pass_fail.sh`, Stefan originally wrote it and I simplified it, so I don't have much to say about what it should or shouldn't be doing with the results.

I'm not opposed to automated PR testing, but testing Nalu-Wind is not trivial and I don't see the resources necessary for CI ever becoming available during this project, nor would I want to be the one to put the effort into making whatever may exist sufficient.

Lastly, I will ask if there is a specific issue we're trying to resolve here, or is this merely a request to change the default tolerances? If so, they can be whatever anyone wants them to be.

**Comment by lucbv** [comment] 2019-06-19 15:10
@jrood-nrel fundamentally my question was: "What do I need to do when I submit a PR"
It eventually moved on to what is a good way to evaluate a PR and what can be expected if we do not all have the same compiler/TPL versions, etc...

**Comment by lucbv** [comment] 2019-06-19 17:00
I finally have a "compatible" local installation of nalu-wind+Trilinos, it turns out that using `SuperLU/5.2.1` leads to diffs whereas `SuperLU/4.3` does not...
I should have realized that it was the likely culprit since I need to add `Trilinos_ENABLE_SuperLU5_API:BOOL=ON` in my configuration and @sayerhs does not...
In any case I have a way of getting clean build and tests on my workstation!

**Comment by sayerhs** [comment] 2019-07-03 22:51
Added options to allow users to specify a custom gold norm dir during CMake configure, and output both absolute and relative tolerance for failing tests. Future discussion regarding CI can be a new issue.

**Closed by sayerhs** 2019-07-03 22:51 UTC
